Tracker:AddLocations("locations/Act 1.json")
Tracker:AddLocations("locations/Act 2.json")
Tracker:AddLocations("locations/Act 3.json")
Tracker:AddLocations("locations/Act 4.json")
Tracker:AddLocations("locations/Act 5.json")

Tracker:AddLocations("locations/Shrine.json")
Tracker:AddLocations("locations/Urn.json")
Tracker:AddLocations("locations/Barrel.json")
Tracker:AddLocations("locations/Chest.json")
Tracker:AddLocations("locations/Set Pickup.json")
Tracker:AddLocations("locations/Gold Milestone.json")
Tracker:AddLocations("locations/Cow.json")
Tracker:AddLocations("locations/Mercenary.json")
Tracker:AddLocations("locations/Hellforge High Rune.json")
Tracker:AddLocations("locations/NPC Dialogue.json")
Tracker:AddLocations("locations/Runeword Crafted.json")
Tracker:AddLocations("locations/Cube Recipe.json")

Tracker:AddLocations("locations/Reach Level.json")
--Tracker:AddLocations("locations/Clear.json")
Tracker:AddLocations("locations/Clear (Act 1).json")
Tracker:AddLocations("locations/Clear (Act 2).json")
Tracker:AddLocations("locations/Clear (Act 3).json")
Tracker:AddLocations("locations/Clear (Act 4).json")
Tracker:AddLocations("locations/Clear (Act 5).json")
--Tracker:AddLocations("locations/Enter.json")
Tracker:AddLocations("locations/Enter (Act 1).json")
Tracker:AddLocations("locations/Enter (Act 2).json")
Tracker:AddLocations("locations/Enter (Act 3).json")
Tracker:AddLocations("locations/Enter (Act 4).json")
Tracker:AddLocations("locations/Enter (Act 5).json")
--Tracker:AddLocations("locations/Waypoint.json")
Tracker:AddLocations("locations/Waypoint (Act 1).json")
Tracker:AddLocations("locations/Waypoint (Act 2).json")
Tracker:AddLocations("locations/Waypoint (Act 3).json")
Tracker:AddLocations("locations/Waypoint (Act 4).json")
Tracker:AddLocations("locations/Waypoint (Act 5).json")
--Tracker:AddLocations("locations/Hunt.json")
Tracker:AddLocations("locations/Hunt (Act 1).json")
Tracker:AddLocations("locations/Hunt (Act 2).json")
Tracker:AddLocations("locations/Hunt (Act 3).json")
Tracker:AddLocations("locations/Hunt (Act 4).json")
Tracker:AddLocations("locations/Hunt (Act 5).json")

Tracker:AddLocations("locations/Overworld.json")
Tracker:AddLocations("locations/Overworld (Act 1).json")
Tracker:AddLocations("locations/Overworld (Act 2).json")
Tracker:AddLocations("locations/Overworld (Act 3).json")
Tracker:AddLocations("locations/Overworld (Act 4).json")
Tracker:AddLocations("locations/Overworld (Act 5).json")
